language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

sudo: false

before_install:
  - travis_retry composer self-update
  - composer install

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit
